import { env } from 'cloudflare:workers';
import { catalogue, ghPrice, ghanaPesewas } from '@/lib/catalogue';
import { storeIdentity, claimGuest, guestCookie } from '@/lib/store-identity';
import { getProductOptionSnapshot } from '@/lib/product-variants';
const products=new Map(catalogue.map(p=>[p.id,p]));
function db(){const v=(env as unknown as {DB:D1Database}).DB;if(!v)throw new Error('Storage unavailable');return v}
function response(data:unknown,cookie='',status=200){return Response.json(data,{status,headers:{'Cache-Control':'no-store',...(cookie?{'Set-Cookie':cookie}:{})}})}
export async function GET(req:Request){let cookie='';try{const identity=await storeIdentity(req,db());const {owner,user,guestOwner}=identity;cookie=identity.cookie;const results=await db().batch([db().prepare('SELECT product,quantity FROM basket WHERE owner=?').bind(owner),db().prepare('SELECT product FROM saved WHERE owner=?').bind(owner),db().prepare('SELECT data FROM profiles WHERE owner=?').bind(owner),db().prepare('SELECT id,kind,data,status,created FROM requests WHERE owner=? ORDER BY created DESC LIMIT 100').bind(owner)]);return response({cart:results[0].results,saved:results[1].results.map((x:any)=>x.product),profile:results[2].results[0]?JSON.parse(String((results[2].results[0] as any).data)):user?{name:user.name,email:user.email}:{},requests:results[3].results.map((x:any)=>({...x,data:JSON.parse(x.data)})),email:user?.email||null,user:user?{name:user.name,email:user.email}:null,guestPending:Boolean(user&&guestOwner)},cookie)}catch{console.error('Store read unavailable');return response({error:'Your saved shopping information is temporarily unavailable. Please try again.'},cookie,503)}}
export async function POST(req:Request){let cookie='';try{const origin=req.headers.get('origin');if(origin!==new URL(req.url).origin)return response({error:'Invalid request origin'},cookie,403);const identity=await storeIdentity(req,db());const {owner,user,guestOwner}=identity;cookie=identity.cookie;const raw=await req.text();if(raw.length>20000)return response({error:'Request is too large'},cookie,413);const body=JSON.parse(raw);const {action}=body;
if(action==='claimGuest'){if(!user)return response({error:'Sign in to save this shopping session to your account.'},cookie,401);if(guestOwner)await claimGuest(db(),guestOwner,owner);return response({ok:true},guestCookie(req,'',0));}
else if(action==='cart'){if(!products.has(body.product)||!Number.isInteger(body.quantity)||body.quantity<0||body.quantity>20)return response({error:'Choose a valid product and a quantity from 1 to 20.'},cookie,400);if(body.quantity===0)await db().prepare('DELETE FROM basket WHERE owner=? AND product=?').bind(owner,body.product).run();else await db().prepare('INSERT INTO basket(owner,product,quantity) VALUES(?,?,?) ON CONFLICT(owner,product) DO UPDATE SET quantity=excluded.quantity').bind(owner,body.product,body.quantity).run();}
else if(action==='save'){if(!products.has(body.product))return response({error:'Product not found'},cookie,400);if(body.value)await db().prepare('INSERT OR IGNORE INTO saved(owner,product) VALUES(?,?)').bind(owner,body.product).run();else await db().prepare('DELETE FROM saved WHERE owner=? AND product=?').bind(owner,body.product).run();}
else if(action==='profile'){const p=body.profile||{};const profile={name:String(p.name||'').slice(0,120),email:String(p.email||'').slice(0,160),phone:String(p.phone||'').slice(0,30),city:String(p.city||'Accra').slice(0,70),address:String(p.address||'').slice(0,300),digitalAddress:String(p.digitalAddress||'').slice(0,50)};await db().prepare('INSERT INTO profiles(owner,data) VALUES(?,?) ON CONFLICT(owner) DO UPDATE SET data=excluded.data').bind(owner,JSON.stringify(profile)).run();}
else if(action==='request'){if(!['quote','service','trade-in','return','business','contact'].includes(body.kind))return response({error:'Choose a valid request type'},cookie,400);const form=body.form||{};if(!String(form.name||'').trim()||!/^\S+@\S+\.\S+$/.test(String(form.email||'')))return response({error:'Your name and a valid email are required.'},cookie,400);const payload:any={name:String(form.name).slice(0,120),email:String(form.email).slice(0,160),phone:String(form.phone||'').slice(0,30),city:String(form.city||'Accra').slice(0,70),address:String(form.address||'').slice(0,300),digitalAddress:String(form.digitalAddress||'').slice(0,50),service:String(form.service||'').slice(0,150),message:String(form.message||'').slice(0,3000),paymentPreference:String(form.paymentPreference||'Mobile money').slice(0,80)};
if(body.kind==='quote'){const basket=await db().prepare('SELECT product,quantity FROM basket WHERE owner=?').bind(owner).all();payload.items=basket.results.map((x:any)=>{const p=products.get(x.product);return p?{id:p.id,name:p.name,quantity:x.quantity,options:getProductOptionSnapshot(p.id),indicativeUnitPrice:ghPrice(p)}:null}).filter(Boolean);if(!payload.items.length)return response({error:'Add a product before requesting a quote.'},cookie,400);payload.indicativeTotal=payload.items.some((i:any)=>i.indicativeUnitPrice!==null)?payload.items.reduce((sum:number,i:any)=>sum+i.quantity*(ghanaPesewas(i.indicativeUnitPrice||0)??0),0)/100:null;payload.unpricedQuantity=payload.items.filter((i:any)=>i.indicativeUnitPrice===null).reduce((n:number,i:any)=>n+i.quantity,0);payload.priceType='Ghana retailer reference, not a binding offer';payload.currency='GHS';payload.paymentStatus='No payment collected';}const id='KR-'+crypto.randomUUID().slice(0,8).toUpperCase();await db().prepare('INSERT INTO requests(id,owner,kind,data,status,created) VALUES(?,?,?,?,?,?)').bind(id,owner,body.kind,JSON.stringify(payload),'Request received',new Date().toISOString()).run();return response({ok:true,id},cookie)}else return response({error:'Unknown action'},cookie,400);return response({ok:true},cookie)}catch{console.error('Store update unavailable');return response({error:'We could not save that change. Your form has been kept. Please try again.'},cookie,503)}}
